### ISSUE TITLE
[F9-meta] initiate efforts to help open-source contributors contribute

### ISSUE THREAD

**Issue by jamesray1** [redgridone/Internet-of-Energy#6]
This issue is pretty broad in scope. However, I'd like to suggest that since the Internet-of-Energy is an open source protocol, it may be helpful to make it easier for people outside of Redgrid to contribute.

Some things that may be helpful include:
- high-level design documents, such as goals (#7), and the proposed architecture of the protocol that can meet these goals (#8)
- examples of use cases, e.g. demand response management; local electricity trading; maybe virtual power plants; asset investment vehicles and ownership (even potentially as a public commons); asset management; environmental commodities trading (e.g., carbon and renewable energy credits); additional community renewable models such as virtual net metering; renewable energy sharing from one system in a multi-unit building to multiple units, a la Allume; markets for or commons with electric vehicle charging/discharging networks; different electricity pricing schemes (e.g. spot pricing, capacity-based pricing, location-relative-to-the-grid-based pricing, etc.); and combinations of these use cases (e.g. virtual power plants to buy power on the cheap, e.g. with spot pricing, or with local electricity trading from e.g. wind generators at night, in order to charge batteries (or other energy storage devices)

It's probably out of scope of the Internet of Energy, but being able to port existing energy use cases over to happs would be handy. One example would be for changing full or partial ownership of organizations, with various funding models, e.g. commonizing them, crowd equity, asset-backed mutual credit cryptocurrencies with the assets, products, and/or services of the org, etc.

**Comment by jameschrray** [comment]
I just saw https://github.com/redgridone/ARCHIVED--mdbook/blob/master/book/pdf/Internet_of_Energy_Book.pdf, it looks like that would address use cases. Same thing for the architecture. Objectives are also addressed for energy currencies. Goals are highlighted on p 1.
